CREATE database Customer_behaviour;
use  Customer_behaviour;

select * from customer limit 20;

-- Q1. what is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as total_revenue 
from customer
group by gender;

-- 	Q2. Which customers used a discount but still spent more then the average purchase_amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3. which are the top 5 products with the highest average review rating?
select Round(avg(review_rating),2)as average_rating_product, item_purchased
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amount between standard and express shipping.
select Round(avg(purchase_amount),2) , shipping_type
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5.Do subscribed customers spend more? Compare average speed and toatal review between subscribers and non-subscribers?
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount),2) AS avg_spend,
    ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- Q6.Which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segement customers into new, Returning and loyal based on their total 
-- number of previous purshases, and show the count of each segment?
with customer_type as(
select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
from customer
)

select customer_segment, count(*) as number_of_customers
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category, item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT 
    item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9. Are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribes?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?->
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;